### PR TITLE
optional params

### PR DESCRIPTION
**Pull request by DanilloCorvalan**
#5

### CODE REVIEW

**Comment by DanilloCorvalan** [comment]
@shawninder :)

**Comment by shawninder** [comment]
Added a test that breaks (when there is a optional parameter before a required parameter).

Also, I think I would prefer `function (required, [optional1], [optional2])` to `function (required [, optional1, optional2])`.

I've seen the former more often, it looks better to me, and it makes more sence when you have more mixed up args: `function (a, [b], [c], d, [e])` VS `function (a [, b, c], d [, e])`

**Comment by DanilloCorvalan** [comment]
@shawninder It's more common to have optional parameters at the end of the function signature, actually I haven't seen it before. This way we avoid having functions calls like `myFunc(1, null, null, 2)`.

**Comment by shawninder** [comment]
@DanilloCorvalan yes I know, but we don't want to cover most cases, or recommended cases. We want to cover all cases. Also, there is the pretty important case of node core module async functions. You always provide the (required) callback as last argument. For example: `fs.readFile(file, [options], callback)`. And you don't use `fs.readFile(file, null, callback)`, you just do `fs.readFile(file, callback)` and `readFile` just figures it out..

**Pull request merged**
